### ISSUE TITLE
PAO crashes when clicking icon

### ISSUE THREAD

**Issue by roflsausage** [SamHurne/gw2pao#51]
Hello, I am having an issue where PAO opens just fine, but when I click the icon in game it crashes. It gives the error "A fatal error has occurred". The log file gives this error message.

"2017-01-05 11:50:49.0898|FATAL|GW2PAO.App|1|System.ArgumentException: StylusPointDescription cannot contain duplicate StylusPointPropertyInfos. Parameter name: stylusPointPropertyInfos"

I am running windows 10 professional. Any help on this issue would be appreciated, I really like the look of this overlay.

**Comment by SamHurne** [comment]
Hmm yea that's very odd. Are you running the tool on a machine with a touchscreen?

**Comment by roflsausage** [comment]
Nope no touchscreen. I do have a Wacom tablet, but I disconnected it. It does seem to be related to that doesn't it?

**Comment by roflsausage** [comment]
Here is the full message relating to that error in case it helps.

2017-01-05 11:55:54.3606|FATAL|GW2PAO.App|1|System.ArgumentException: StylusPointDescription cannot contain duplicate StylusPointPropertyInfos.
Parameter name: stylusPointPropertyInfos
   at System.Windows.Input.StylusPointDescription..ctor(IEnumerable`1 stylusPointPropertyInfos)
   at System.Windows.Input.TabletDeviceBase.get_StylusPointDescription()
   at System.Windows.Input.StylusPointer.PointerTabletDevice.UpdateSizeDeltas()
   at System.Windows.Input.StylusPointer.PointerTabletDevice..ctor(PointerTabletDeviceInfo deviceInfo)
   at System.Windows.Input.StylusPointer.PointerTabletDeviceCollection.Refresh()
   at System.Windows.Input.StylusPointer.PointerLogic.get_TabletDevices()
   at System.Windows.Input.StylusPointer.PointerLogic.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by roflsausage** [comment]
Hey sorry to spam you, I'm sure you are quite busy. Just wanted to let you know I resolved my problem by uninstalling the drivers for my drawing tablet and restarting, so it does appear to be related to that. I rarely use it so I don't mind, but just thought I would let you know the root of the problem in case others experience it in the future.

**Comment by SamHurne** [comment]
Ok thanks for the update! Definitely an odd one, and based on the limited searching I did on the exception text, it might have been an issue that would impact other applications on your machine as well.
